apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "stunnel.fullname" . }}-services
  labels:
    app: {{ template "stunnel.name" . }}
    chart: {{ template "stunnel.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
{{- range .Values.services }}
  {{ .name }}.conf: |-
    [{{ .name }}]
    accept = {{ $.Values.bind }}:{{ .port }}
{{- with .config }}
{{- range $key, $value := .config }}
  {{- if ne $key "accept" }}
    {{ $key }} = {{ $value }}
  {{- end -}}
{{- end }}
{{- end }}
{{- end }}
